### PR TITLE
1.20

### LINKED ISSUE #8: Update search to 1.20?

### PR DESCRIPTION
**Pull request by Legoman99573**
Add 1.20 as an option. Closes #8

### CODE REVIEW

**Comment by fof1092** [comment]
Thank you! :)
I will take care next week that the backend is up to date.

**Comment by Legoman99573** [comment]
Aight. Thought I would go ahead and include the section. Upon testing, it shows up the older items just fine if the 1.20 tag is included 😄

**Comment by TheMikol** [comment]
Pls update

**Comment by DanyGreaver** [comment]
> Aight. Thought I would go ahead and include the section. Upon testing, it shows up the older items just fine if the 1.20 tag is included 😄

Hii 
is it possible to download your version of the extension please. since the Author hasn't pushed the update yet.

**Comment by fof1092** [comment]
The update will be released tomorrow, I'll probably write a bit more about it then.

**Comment by fof1092** [comment]
Since I had to change a few more things, I included the update differently, but for Minecraft 1.21 I would be very happy about a new pull request! :)

**Pull request closed without merging**
